# Generated by Django 3.0.2 on 2020-01-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=50)),
                ('user2', models.CharField(max_length=50)),
                ('user1_input', models.CharField(choices=[('가위', '가위'), ('바위', '바위'), ('보', '보')], max_length=10)),
                ('user2_input', models.CharField(choices=[('가위', '가위'), ('바위', '바위'), ('보', '보')], max_length=10)),
            ],
        ),
    ]
